### PR TITLE
Fix multiple call to `callback` on error.

### PR DESCRIPTION
**Pull request by thomas-riccardi**

### CODE REVIEW

**Comment by yan-foto** [comment]
Good observation! However, I rather not `return callback`s, for the sake of readability. I would suggest something like this:

``` js
protocol.interceptBufferProtocol('file', function(request, callback) {
  var file = getPath(request.url);
  var content = null;

  // See if file actually exists
  try {
    content = fs.readFileSync(file);

    var ext = path.extname(file);
    if (ext === '.jade') {
      var compiled = jade.compileFile(file, jadeOptions)(locals);

      callback({data: new Buffer(compiled), mimeType:'text/html'});
    } else {
      callback({data: content, mimeType: mime.lookup(ext)});
    }
  } catch (e) {
    // See here for error numbers:
    // https://code.google.com/p/chromium/codesearch#chromium/src/net/base/net_error_list.h
    if (e.code === 'ENOENT') {
      // NET_ERROR(FILE_NOT_FOUND, -6)
      callback(6);
    } else {
      // All other possible errors return a generic failure
      // NET_ERROR(FAILED, -2)
      callback(2);
    }
  }
}, function (error, scheme) {
  if (!error) {
    console.log('Jade interceptor registered successfully');
  } else {
    console.error('Jade interceptor failed:', error);
  }
});
```

**Comment by thomas-riccardi** [comment]
`return cb(...);` (or `cb(...); return;` if you want to avoid some jshint warnings) is a standard pattern in node.js, especially for error cases.

**Comment by yan-foto** [comment]
That is true, my suggestion may even complicate stuff :confused: ! I will merge this manually though to bump the version and add return to all other callbacks.

**Comment by thomas-riccardi** [comment]
The non error callbacks calls are at the end of their branches, so there is no need for an explicit return, although it's coding style at this point.
Version bumping could be done in a separate commit.

**Comment by yan-foto** [comment]
You may have noticed that I have a bit of OCD when it comes to the code! returning all the callbacks will also avoid any eventual warnings by linters in addition to a unified coding style. I will take care of this later.

**Comment by yan-foto** [comment]
@triccardi-systran I really appreciate your help. I merged the pull request and leard about idomatic callback handling :+1:

**Pull request merged**
